title: What Decade Is This Date?
author:
  name: Matthew Miner
  email: mminer237@gmail.com
  site: https://matthewminer.name
url: https://whatdecadeisthis.date
tagManagerCode: GTM-TK37G57
# googleAdClient: ca-pub-5576042369154755
themeColor: "#222222"

# googleFonts:
#   - Lato:400,400i,900
#   - Old+Standard+TT:400,400i,700
#   - IBM+Plex+Serif:500,500i

lastYear: 3000

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

collections:
  pages:
    output: true

permalink: /:path

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - generator