title: What Decade Is This Date?
author:
  name: Matthew Miner
  email: mminer237@gmail.com
  site: https://matthewminer.name
url: https://whatdecadeisthis.date
googleAdClient: ca-pub-5576042369154755
themeColor: "#222222"

lastYear: 3000

incremental: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "_tv/*/"
    values:
      layout: "tv-episode"
  -
    scope:
      path: "_tv/*/index.md"
    values:
      layout: "tv-index"

collections:
  pages:
    output: true
    permalink: /:name
  decades:
    output: false
  tv:
    output: true
    permalink: /:collection/:path

permalink: /:name

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - generator
  
include:
  - _redirects
